# Generated by Django 4.1.5 on 2025-05-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "view_status",
                    models.BooleanField(default=False, verbose_name="View Status"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Information", "Information"),
                            ("Success", "Success"),
                            ("Warning", "Warning"),
                            ("Error", "Error"),
                        ],
                        default="Information",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
