services:
  back:
    image: iust-backend
    container_name: back_django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - back-network
    volumes:
      - ./src:/app
      - ./media:/app/media
    depends_on:
      - db
      - redis
    command: >
      sh -c "
      python manage.py compilemessages &&
      python manage.py migrate &&
      gunicorn Abrat.wsgi:application --bind 0.0.0.0:8000
      "

  db:
    image: postgres:latest
    container_name: back_postgres
    env_file: .env.db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - back-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: back_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - back-network

volumes:
  postgres_data:

networks:
  back-network:
    driver: bridge
