# Generated by Django 4.1.5 on 2025-05-10 07:19

import app_chat.models.chat_room
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Title")),
                (
                    "room_id",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Room Id"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting_For_An_Answer", "Waiting For An Answer"),
                            ("Has_Been_Answered", "Has Been Answered"),
                            ("Closed", "Closed"),
                        ],
                        default="Waiting_For_An_Answer",
                        max_length=21,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="LOW",
                        max_length=6,
                        verbose_name="Priority",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=app_chat.models.chat_room.ticket_image_directory_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatroom_messages",
                        to="app_chat.chatroom",
                        verbose_name="Chat Room",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
    ]
