# Generated by Django 4.1.5 on 2024-09-10 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_chat", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="members",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Admin",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
