# Generated by Django 4.1.5 on 2025-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_address_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sso_signup",
            field=models.BooleanField(default=False),
        ),
    ]
