# Generated by Django 4.1.5 on 2025-05-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0003_user_sso_signup"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="iran_phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Iran Phone Number"
            ),
        ),
    ]
