# Generated by Django 4.1.5 on 2024-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0006_profile_passport_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_issuance_letter",
            field=models.BooleanField(
                default=False, verbose_name="Can Issuance Letter"
            ),
        ),
    ]
