# Generated by Django 4.1.5 on 2024-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0007_user_can_issuance_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="english_status",
            field=models.CharField(
                choices=[
                    ("Weak", "Weak"),
                    ("Good", "Good"),
                    ("Excellent", "Excellent"),
                ],
                default="Good",
                max_length=9,
                verbose_name="English Status",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("FeMale", "FeMale"), ("Other", "Other")],
                default="Male",
                max_length=6,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="persian_status",
            field=models.CharField(
                choices=[
                    ("Weak", "Weak"),
                    ("Good", "Good"),
                    ("Excellent", "Excellent"),
                ],
                default="Good",
                max_length=9,
                verbose_name="Persian Status",
            ),
        ),
    ]
