# Generated by Django 4.1.5 on 2025-05-10 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BachelorDegree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "date_of_graduation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Of Graduation"
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="GPA",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Field Of Study",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="University"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bachelor Degree",
                "verbose_name_plural": "Bachelor Degrees",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "fa_name",
                    models.CharField(max_length=128, verbose_name="Faculty Name"),
                ),
                (
                    "en_name",
                    models.CharField(max_length=128, verbose_name="English Name"),
                ),
                (
                    "ar_name",
                    models.CharField(max_length=128, verbose_name="Arabic Name"),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("P.H.D", "P.H.D"),
                        ],
                        default="Bachelor",
                        max_length=8,
                        verbose_name="Degree",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "fa_name",
                    models.CharField(max_length=128, verbose_name="Faculty Name"),
                ),
                (
                    "en_name",
                    models.CharField(max_length=128, verbose_name="English Name"),
                ),
                (
                    "ar_name",
                    models.CharField(max_length=128, verbose_name="Arabic Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "requires_an_interview",
                    models.BooleanField(
                        default=False, verbose_name="Require Interview"
                    ),
                ),
                (
                    "max_members",
                    models.PositiveSmallIntegerField(verbose_name="Max Members"),
                ),
            ],
            options={
                "verbose_name": "Field of Study",
                "verbose_name_plural": "Fields of Study",
            },
        ),
        migrations.CreateModel(
            name="HighSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "date_of_graduation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Of Graduation"
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="GPA",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Field Of Study",
                    ),
                ),
            ],
            options={
                "verbose_name": "High School",
                "verbose_name_plural": "High Schools",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MasterDegree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "date_of_graduation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Of Graduation"
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="GPA",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Field Of Study",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="University"
                    ),
                ),
            ],
            options={
                "verbose_name": "MasterDegree",
                "verbose_name_plural": "Master Degrees",
                "ordering": ["-id"],
            },
        ),
    ]
