# Generated by Django 4.1.5 on 2025-05-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_education", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterdegree",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_master_degree",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="highschool",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_high_school",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="fieldofstudy",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields_of_studies",
                to="app_education.faculty",
                verbose_name="Faculty",
            ),
        ),
        migrations.AddField(
            model_name="bachelordegree",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_bachelor_degree",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
