# Generated by Django 4.1.5 on 2025-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="degree",
            field=models.CharField(
                choices=[
                    ("Bachelor", "Bachelor"),
                    ("Master", "Master"),
                    ("P.H.D", "PhD"),
                ],
                default="Bachelor",
                max_length=8,
                verbose_name="Degree",
            ),
        ),
    ]
