# Generated by Django 4.1.5 on 2025-01-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bachelordegree",
            name="state",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="highschool",
            name="state",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="masterdegree",
            name="state",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="City"
            ),
        ),
    ]
