# Generated by Django 4.1.5 on 2025-05-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_education', '0003_alter_faculty_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_education.faculty', verbose_name='Faculty')),
                ('fields', models.ManyToManyField(to='app_education.fieldofstudy', verbose_name='Fields')),
            ],
            options={
                'verbose_name': 'Faculty Group',
                'verbose_name_plural': 'Faculty Groups',
            },
        ),
    ]
