# Generated by Django 4.1.5 on 2025-04-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0003_bachelordegree_state_highschool_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "fa_name",
                    models.CharField(max_length=64, verbose_name="Faculty Name"),
                ),
                (
                    "en_name",
                    models.CharField(max_length=64, verbose_name="English Name"),
                ),
                (
                    "ar_name",
                    models.CharField(max_length=64, verbose_name="Arabic Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=35, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "fa_name",
                    models.CharField(max_length=64, verbose_name="Faculty Name"),
                ),
                (
                    "en_name",
                    models.CharField(max_length=64, verbose_name="English Name"),
                ),
                (
                    "ar_name",
                    models.CharField(max_length=64, verbose_name="Arabic Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "requires_an_interview",
                    models.BooleanField(
                        default=False, verbose_name="Require Interview"
                    ),
                ),
                (
                    "max_members",
                    models.PositiveSmallIntegerField(verbose_name="Max Members"),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_education.faculty",
                        verbose_name="Faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field of Study",
                "verbose_name_plural": "Fields of Study",
            },
        ),
    ]
