# Generated by Django 4.1.5 on 2025-05-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0004_faculty_fieldofstudy"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="degree",
            field=models.CharField(
                choices=[
                    ("Bachelor", "Bachelor"),
                    ("Master", "Master"),
                    ("P.H.D", "P.H.D"),
                ],
                default="Bachelor",
                max_length=8,
                verbose_name="Degree",
            ),
        ),
    ]
