# Generated by Django 4.1.5 on 2025-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0004_facultygroups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldofstudy",
            old_name="is_active",
            new_name="master_active",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="degree",
        ),
        migrations.AddField(
            model_name="fieldofstudy",
            name="phd_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
