# Generated by Django 4.1.5 on 2025-06-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0005_rename_is_active_fieldofstudy_master_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultygroups",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_groups",
                to="app_education.faculty",
                verbose_name="Faculty",
            ),
        ),
        migrations.AlterField(
            model_name="facultygroups",
            name="fields",
            field=models.ManyToManyField(
                related_name="field_groups",
                to="app_education.fieldofstudy",
                verbose_name="Fields",
            ),
        ),
    ]
