# Generated by Django 4.1.5 on 2025-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0005_faculty_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="ar_name",
            field=models.CharField(max_length=128, verbose_name="Arabic Name"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="en_name",
            field=models.CharField(max_length=128, verbose_name="English Name"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="fa_name",
            field=models.CharField(max_length=128, verbose_name="Faculty Name"),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="ar_name",
            field=models.CharField(max_length=128, verbose_name="Arabic Name"),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="en_name",
            field=models.CharField(max_length=128, verbose_name="English Name"),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="fa_name",
            field=models.CharField(max_length=128, verbose_name="Faculty Name"),
        ),
    ]
