# Generated by Django 4.1.5 on 2025-05-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0006_alter_faculty_ar_name_alter_faculty_en_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldofstudy",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_faculty",
                to="app_education.faculty",
                verbose_name="Faculty",
            ),
        ),
    ]
