# Generated by Django 4.1.5 on 2025-05-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0007_alter_fieldofstudy_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldofstudy",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields_of_studies",
                to="app_education.faculty",
                verbose_name="Faculty",
            ),
        ),
    ]
