# Generated by Django 4.1.5 on 2025-05-10 07:19

import app_application.models.application
import app_application.models.documents
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Tracking ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "applied_program",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Applied Program"
                    ),
                ),
                (
                    "financial_self_support",
                    models.BooleanField(
                        default=False, verbose_name="Financial Self Support"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not_Completed", "Not Completed"),
                            ("Current", "Current"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Need_To_Edit", "Need To Edit"),
                        ],
                        default="Not_Completed",
                        max_length=13,
                        verbose_name="Status",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("P.H.D", "P.H.D"),
                        ],
                        default="Bachelor",
                        max_length=8,
                        verbose_name="Degree",
                    ),
                ),
                ("step", models.IntegerField(default=3, verbose_name="step")),
                (
                    "application_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.application.application_file_directory_path,
                        verbose_name="Application File",
                    ),
                ),
                (
                    "application_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.application.application_file_directory_path,
                        verbose_name="Application Letter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "curriculum_vitae",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Curriculum Vitae",
                    ),
                ),
                (
                    "personal_photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Personal photo",
                    ),
                ),
                (
                    "valid_passport",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Valid",
                    ),
                ),
                (
                    "high_school_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="High School Certificate",
                    ),
                ),
                (
                    "trans_script_high_school_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Trans Script High School Certificate",
                    ),
                ),
                (
                    "bachelor_degree",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Bachelor Degree",
                    ),
                ),
                (
                    "trans_script_bachelor_degree",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Trans Script Bachelor Degree",
                    ),
                ),
                (
                    "master_degree",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Master Degree",
                    ),
                ),
                (
                    "trans_script_master_degree",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Trans Script Master Degree",
                    ),
                ),
                (
                    "supporting_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_application.models.documents.document_image_directory_path,
                        validators=[utils.validators.validate_image_file],
                        verbose_name="Supporting Letter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Is Enabled"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Confirmation", "Confirmation"),
                            ("Rejection", "Rejection"),
                            ("Investigation", "Investigation"),
                            ("Referral", "Referral"),
                            ("NeedToEdit", "Need To Edit"),
                        ],
                        default="Investigation",
                        max_length=13,
                        verbose_name="Status",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_timeline",
                        to="app_application.application",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
