# Generated by Django 4.1.5 on 2025-05-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_application", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_education", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeline",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_timeline",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_referral",
                to="app_application.application",
                verbose_name="Application",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="destination_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_user_referral",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destination User",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="origin_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_user_referral",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Origin User",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_document",
                to="app_application.application",
                verbose_name="Application",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent Email",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculty_applications",
                to="app_education.faculty",
                verbose_name="Faculty",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="field_of_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="field_of_study_applications",
                to="app_education.fieldofstudy",
                verbose_name="Field Of Study",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_application",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
