# Generated by Django 4.1.5 on 2025-05-15 14:12

import app_application.models.documents
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="second_supporting_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app_application.models.documents.document_image_directory_path,
                validators=[utils.validators.validate_image_file],
                verbose_name="Supporting Letter",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="third_supporting_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app_application.models.documents.document_image_directory_path,
                validators=[utils.validators.validate_image_file],
                verbose_name="Supporting Letter",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="degree",
            field=models.CharField(
                choices=[
                    ("Bachelor", "Bachelor"),
                    ("Master", "Master"),
                    ("P.H.D", "PhD"),
                ],
                default="Bachelor",
                max_length=8,
                verbose_name="Degree",
            ),
        ),
    ]
