# Generated by Django 4.1.5 on 2024-04-04 16:49

import app_application.models.application
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0011_alter_application_financial_self_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="application_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app_application.models.application.application_file_directory_path,
                verbose_name="Application Letter",
            ),
        ),
    ]
