# Generated by Django 4.1.5 on 2024-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0012_application_application_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("Department of Test", "Department of Test"),
                    ("Department of Chemistry", "Department of Chemistry"),
                    (
                        "Department of Foreign Language",
                        "Department of Foreign Language",
                    ),
                    (
                        "School of Architecture and Environmental Design",
                        "School of Architecture and Environmental Design",
                    ),
                    (
                        "School of Automotive Engineering",
                        "School of Automotive Engineering",
                    ),
                    (
                        "School of Chemical Petroleum and Gas Engineering",
                        "School of Chemical Petroleum and Gas Engineering",
                    ),
                    ("School of Civil Engineering", "School of Civil Engineering"),
                    (
                        "School of Computer Engineering",
                        "School of Computer Engineering",
                    ),
                    (
                        "School of Electrical Engineering",
                        "School of Electrical Engineering",
                    ),
                    (
                        "School of Industrial Engineering",
                        "School of Industrial Engineering",
                    ),
                    ("School of Mathematics", "School of Mathematics"),
                    (
                        "School of Mechanical Engineering",
                        "School of Mechanical Engineering",
                    ),
                    (
                        "School of Metallurgy and Materials Engineering",
                        "School of Metallurgy and Materials Engineering",
                    ),
                    (
                        "School of Advanced Technologies",
                        "School of Advanced Technologies",
                    ),
                    ("School of Physics", "School of Physics"),
                    (
                        "School of Management Economy and Progress Engineering",
                        "School of Management Economy and Progress Engineering",
                    ),
                    ("School of Railway Engineering", "School of Railway Engineering"),
                ],
                max_length=80,
                verbose_name="Faculty",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="field_of_study",
            field=models.CharField(
                choices=[
                    ("Test", "Test"),
                    ("Architecture", "Architecture"),
                    ("Industrial Design", "Industrial Design"),
                    ("Chemical Engineering", "Chemical Engineering"),
                    ("Civil Engineering", "Civil Engineering"),
                    ("Hardware Engineering", "Hardware Engineering"),
                    ("Software Engineering", "Software Engineering"),
                    ("Communication Systems", "Communication Systems"),
                    ("Power Systems", "Power Systems"),
                    ("Electronics", "Electronics"),
                    ("Control Systems", "Control Systems"),
                    ("Industrial Engineering", "Industrial Engineering"),
                    (
                        "Mathematics and Its Applications",
                        "Mathematics and Its Applications",
                    ),
                    ("Mechanical Engineering", "Mechanical Engineering"),
                    (
                        "Material and Metallurgical Engineering",
                        "Material And Metallurgical Engineering",
                    ),
                    ("Atomic and Molecular Physics", "Atomic and Molecular Physics"),
                    ("Solid State Physics", "Solid State Physics"),
                    (
                        "Railway Transportation Engineering",
                        "Railway Transportation Engineering",
                    ),
                    (
                        "Railway Rolling Stock Engineering",
                        "Railway Rolling Stock Engineering",
                    ),
                    (
                        "Railway Track and Structures Engineering",
                        "Railway Track and Structures Engineering",
                    ),
                    ("Analytical Chemistry", "Analytical Chemistry"),
                    ("Inorganic Chemistry", "Inorganic Chemistry"),
                    ("Organic Chemistry", "Organic Chemistry"),
                    ("Physical Chemistry", "Physical Chemistry"),
                    ("Nano-Chemistry", "Nano-Chemistry"),
                    (
                        "Teaching English as a Foreign Language",
                        "Teaching English As A Foreign Language",
                    ),
                    ("Regional Planning", "Regional Planning"),
                    ("Architecture - Housing", "Architecture - Housing"),
                    ("Architecture - Sustainable", "Architecture - Sustainable"),
                    ("Architecture - Technology", "Architecture - Technology"),
                    (
                        "Architecture - Cultural and Educational Spaces",
                        "Architecture Cultural And Educational Spaces",
                    ),
                    (
                        "Architecture - Health Care Spaces",
                        "Architecture - Health Care Spaces",
                    ),
                    ("Land Spaces Architecture", "Land Spaces Architecture"),
                    (
                        "Conservation and Restoration of Historical Buildings and Fabrics – Conservation and Restoration of Urban Heritage",
                        "Conservation And Restoration Of Historical Buildings And Fabrics Conservation And Restoration Of Urban Heritage",
                    ),
                    (
                        "Conservation and Restoration of Historical Buildings and Fabrics – Conservation and Restoration of Architectural Heritage",
                        "Conservation And Restoration Of Historical Buildings And Fabrics Conservation And Restoration Of Architectural Heritage",
                    ),
                    ("Urban Design", "Urban Design"),
                    ("Urban Planning", "Urban Planning"),
                    (
                        "Automotive Engineering - Automobile Dynamic Systems Design",
                        "Automotive Engineering Automobile Dynamic Systems Design",
                    ),
                    (
                        "Automotive Engineering - Power Train",
                        "Automotive Engineering - Power Train",
                    ),
                    (
                        "Automotive Engineering - Body and Structure",
                        "Automotive Engineering Body And Structure",
                    ),
                    (
                        "Automotive Engineering - Automotive Electronics & Electrical Engineering",
                        "Automotive Engineering Automotive Electronics Electrical Engineering",
                    ),
                    (
                        "Process Modeling Simulation & Control",
                        "Process Modeling Simulation Control",
                    ),
                    ("Mineral_Chemical_Engineering", "Mineral Chemical Engineering"),
                    ("Separation Processes", "Separation Processes"),
                    ("Kinetic and Catalysis", "Kinetic and Catalysis"),
                    ("Thermodynamics", "Thermodynamics"),
                    ("Polymer Engineering", "Polymer Engineering"),
                    (
                        "Hydrocarbon Reservoir Engineering",
                        "Hydrocarbon Reservoir Engineering",
                    ),
                    ("Process Design Engineering", "Process Design Engineering"),
                    ("Structural Engineering", "Structural Engineering"),
                    ("Earthquake Engineering", "Earthquake Engineering"),
                    (
                        "Construction Management and Engineering",
                        "Construction Management And Engineering",
                    ),
                    ("Geotechnical Engineering", "Geotechnical Engineering"),
                    (
                        "Road and Transportation Engineering",
                        "Road and Transportation Engineering",
                    ),
                    ("Transportation", "Transportation"),
                    ("Water Resources Management", "Water Resources Management"),
                    (
                        "Water Engineering and Hydraulic Structures",
                        "Water Engineering And Hydraulic Structures",
                    ),
                    ("Environmental Engineering", "Environmental Engineering"),
                    ("Marine Structures Engineering", "Marine Structures Engineering"),
                    (
                        "Artificial Intelligence & Robotics",
                        "Artificial Intelligence & Robotics",
                    ),
                    ("Computer Systems Architecture", "Computer Systems Architecture"),
                    (
                        "Computer Engineering - Computer Networks",
                        "Computer Engineering - Computer Networks",
                    ),
                    ("Bio-Electrics", "Bio-Electrics"),
                    ("Digital Electronic Systems", "Digital Electronic Systems"),
                    (
                        "Electronic Integrated Circuits",
                        "Electronic Integrated Circuits",
                    ),
                    (
                        "Electrical Machines and Power Electronics",
                        "Electrical Machines And Power Electronics",
                    ),
                    (
                        "Electromagnetic Fields and Waves",
                        "Electromagnetic Fields and Waves",
                    ),
                    (
                        "Information Technology Engineering - Electronic Commerce",
                        "Information Technology Engineering - Electronic Commerce",
                    ),
                    ("Systems Optimization", "Systems Optimization"),
                    (
                        "Supply Chain and Logistic Engineering",
                        "Supply Chain and Logistic Engineering",
                    ),
                    ("Engineering Management", "Engineering Management"),
                    ("Socio-Economic Macro Systems", "Socio-Economic Macro Systems"),
                    ("Project Management", "Project Management"),
                    ("Financial Engineering", "Financial Engineering"),
                    ("Pure Mathematics - Algebra", "Pure Mathematics - Algebra"),
                    ("Pure Mathematics - Geometry", "Pure Mathematics - Geometry"),
                    ("Pure Mathematics - Analysis", "Pure Mathematics - Analysis"),
                    (
                        "Applied Mathematics - Numerical Analysis",
                        "Applied Mathematics Numerical Analysis",
                    ),
                    (
                        "Applied Mathematics - Operation Research",
                        "Applied Mathematics Operation Research",
                    ),
                    ("Mathematics Statistics", "Mathematics Statistics"),
                    ("Applied Design", "Applied Design"),
                    ("Energy Conversion", "Energy Conversion"),
                    ("Manufacturing", "Manufacturing"),
                    ("Biomechanics", "Biomechanics"),
                    ("Extractive Metallurgy", "Extractive Metallurgy"),
                    ("Ceramics Engineering", "Ceramics Engineering"),
                    ("Materials Selection", "Materials Selection"),
                    ("Bio-Materials", "Bio-Materials"),
                    ("Metals Casting", "Metals Casting"),
                    ("Metals Forming", "Metals Forming"),
                    ("Nanotechnology - Materials", "Nanotechnology - Materials"),
                    (
                        "Energy Systems - Energy and Environment",
                        "Energy Systems - Energy and Environment",
                    ),
                    ("Satellite Engineering", "Satellite Engineering"),
                    ("Photonics", "Photonics"),
                    ("Condensed Matter Physics", "Condensed Matter Physics"),
                    ("Laser Optics Physics", "Laser Optics Physics"),
                    (
                        "Master of Business Administration (MBA) - Marketing",
                        "Master of Business Administration (MBA) - Marketing",
                    ),
                    (
                        "Master of Business Administration (MBA) - Strategy",
                        "Master of Business Administration (MBA) - Strategy",
                    ),
                    (
                        "Management of Technology (MOT) - Technological Innovation",
                        "Management of Technology (MOT) - Technological Innovation",
                    ),
                    (
                        "Management of Technology (MOT) - Technological Transfer",
                        "Management of Technology (MOT) - Technological Transfer",
                    ),
                    (
                        "Management of Technology (MOT) - Research & Development Policies",
                        "Management of Technology (MOT) - Research & Development Policies",
                    ),
                    (
                        "Information Technology Management-E-Business",
                        "Information Technology Management-E-Business",
                    ),
                    (
                        "Entrepreneurship - New Businesses",
                        "Entrepreneurship - New Businesses",
                    ),
                    (
                        "Industrial Engineering - Macro Systems",
                        "Industrial Engineering - Macro Systems",
                    ),
                    (
                        "Economic Development and Planning",
                        "Economic Development and Planning",
                    ),
                    ("Economic Systems Planning", "Economic Systems Planning"),
                    ("Electric Railways Engineering", "Electric Railways Engineering"),
                    ("Railway Safety Engineering", "Railway Safety Engineering"),
                    ("Railway Control and Signaling", "Railway Control and Signaling"),
                    ("Urbanism", "Urbanism"),
                    ("Quality & Productivity", "Quality & Productivity"),
                    (
                        "Applied Mathematics - Statistics",
                        "Applied Mathematics - Statistics",
                    ),
                    (
                        "Dynamics Control and Vibration",
                        "Dynamics Control and Vibration",
                    ),
                    ("Solid Mechanics", "Solid Mechanics"),
                    ("Materials Engineering", "Materials Engineering"),
                    (
                        "Management of Iranian Public Organization",
                        "Management of Iranian Public Organization",
                    ),
                    ("Science of Technology Policy", "Science of Technology Policy"),
                ],
                max_length=150,
                verbose_name="Field Of Study",
            ),
        ),
    ]
