# Generated by Django 4.1.5 on 2024-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FrequentlyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
            ],
            options={
                "verbose_name": "Frequently Question",
                "verbose_name_plural": "Frequently Questions",
                "ordering": ["-id"],
            },
        ),
    ]
