# Generated by Django 4.1.5 on 2025-04-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fa_signup_terms",
                    models.TextField(verbose_name="Farsi Signup terms"),
                ),
                (
                    "en_signup_terms",
                    models.TextField(verbose_name="English Signup terms"),
                ),
                (
                    "ar_signup_terms",
                    models.TextField(verbose_name="Arabic Signup terms"),
                ),
                (
                    "fa_before_sign_text",
                    models.TextField(verbose_name="Farsi Before sign text"),
                ),
                (
                    "en_before_sign_text",
                    models.TextField(verbose_name="English Before sign text"),
                ),
                (
                    "ar_before_sign_text",
                    models.TextField(verbose_name="Arabic Before sign text"),
                ),
                (
                    "fa_before_new_application_text",
                    models.TextField(verbose_name="Farsi Before new application text"),
                ),
                (
                    "en_before_new_application_text",
                    models.TextField(
                        verbose_name="English Before new application text"
                    ),
                ),
                (
                    "ar_before_new_application_text",
                    models.TextField(verbose_name="Arabic Before new application text"),
                ),
                (
                    "admin_application_text",
                    models.TextField(verbose_name="Admin application text"),
                ),
                (
                    "start_application_date",
                    models.DateField(verbose_name="Start application date"),
                ),
                (
                    "end_application_date",
                    models.DateField(verbose_name="End application date"),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
