# Generated by Django 4.1.5 on 2025-05-25 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="admin_application_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="ar_before_new_application_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="ar_before_sign_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="ar_signup_terms",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="en_before_new_application_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="en_before_sign_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="en_signup_terms",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="end_application_date",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="fa_before_new_application_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="fa_before_sign_text",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="fa_signup_terms",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="start_application_date",
        ),
        migrations.AddField(
            model_name="settings",
            name="end_register_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="End register date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="start_register_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Start register date"
            ),
            preserve_default=False,
        ),
    ]
