# Generated by Django 4.1.5 on 2025-06-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_education", "0005_rename_is_active_fieldofstudy_master_active_and_more"),
        ("app_admin", "0003_remove_settings_admin_application_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="schools",
        ),
        migrations.AddField(
            model_name="admin",
            name="faculties",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.faculty",
                verbose_name="Schools",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admin",
            name="fields",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.facultygroups",
                verbose_name="Fields",
            ),
        ),
    ]
