# Generated by Django 4.1.5 on 2025-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0004_remove_admin_schools_admin_faculties_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="ar_terms",
            field=models.TextField(blank=True, null=True, verbose_name="Arabic terms"),
        ),
        migrations.AddField(
            model_name="settings",
            name="end_terms",
            field=models.TextField(blank=True, null=True, verbose_name="English terms"),
        ),
        migrations.AddField(
            model_name="settings",
            name="fa_terms",
            field=models.TextField(blank=True, null=True, verbose_name="Farsi terms"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="end_register_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="End register date"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="start_register_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start register date"
            ),
        ),
    ]
