# Generated by Django 4.1.5 on 2025-06-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0005_settings_ar_terms_settings_end_terms_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="end_terms",
            new_name="en_terms",
        ),
    ]
