# Generated by Django 4.1.5 on 2025-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_rename_end_terms_settings_en_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='end_phd_register_date',
            field=models.DateField(blank=True, null=True, verbose_name='End PHD register date'),
        ),
        migrations.AddField(
            model_name='settings',
            name='start_phd_register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start PHD register date'),
        ),
    ]
