# Generated by Django 4.1.5 on 2024-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin", "0007_alter_admin_fields_alter_admin_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="schools",
            field=models.CharField(
                choices=[
                    ("Department of Chemistry", "Department of Chemistry"),
                    (
                        "Department of Foreign Language",
                        "Department of Foreign Language",
                    ),
                    (
                        "School of Architecture and Environmental Design",
                        "School of Architecture and Environmental Design",
                    ),
                    (
                        "School of Automotive Engineering",
                        "School of Automotive Engineering",
                    ),
                    (
                        "School of Chemical Petroleum and Gas Engineering",
                        "School of Chemical Petroleum and Gas Engineering",
                    ),
                    ("School of Civil Engineering", "School of Civil Engineering"),
                    (
                        "School of Computer Engineering",
                        "School of Computer Engineering",
                    ),
                    (
                        "School of Electrical Engineering",
                        "School of Electrical Engineering",
                    ),
                    (
                        "School of Industrial Engineering",
                        "School of Industrial Engineering",
                    ),
                    ("School of Mathematics", "School of Mathematics"),
                    (
                        "School of Mechanical Engineering",
                        "School of Mechanical Engineering",
                    ),
                    (
                        "School of Metallurgy and Materials Engineering",
                        "School of Metallurgy and Materials Engineering",
                    ),
                    (
                        "School of Advanced Technologies",
                        "School of Advanced Technologies",
                    ),
                    ("School of Physics", "School of Physics"),
                    (
                        "School of Management Economy and Progress Engineering",
                        "School of Management Economy and Progress Engineering",
                    ),
                    ("School of Railway Engineering", "School of Railway Engineering"),
                ],
                max_length=128,
                verbose_name="Schools",
            ),
        ),
    ]
